# Generated by Django 4.2.11 on 2024-04-21 15:06

from django.db import migrations, models
import django.db.models.deletion
import predict_telegram_bot.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionOfStudy',
            fields=[
                ('direction_of_study', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('local_name', models.CharField(default='КН-', max_length=10, validators=[predict_telegram_bot.validate.validate_local_group], verbose_name='Внутреннее название')),
                ('global_name', models.CharField(default='МЕН-', max_length=10, primary_key=True, serialize=False, validators=[predict_telegram_bot.validate.validate_global_group], verbose_name='Внешнее название')),
                ('direction_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict_telegram_bot.directionofstudy', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Студенческий билет')),
                ('full_name', models.CharField(default='Не указано', max_length=45, verbose_name='Ф.И.О')),
                ('olympiad', models.CharField(choices=[('Участвовал', 'Участвовал'), ('Не участвовал', 'Не участвовал'), ('Не выбрано', 'Не выбрано')], default='Не выбрано', max_length=100, verbose_name='Участие/неучастие в олимпиадах')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict_telegram_bot.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='StudySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=10, verbose_name='Название предмета')),
                ('direction_of_study', models.ManyToManyField(default=None, to='predict_telegram_bot.directionofstudy', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='StudyExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.FloatField(default=0, verbose_name='Итоговый балл')),
                ('exam_predict', models.FloatField(default=0, editable=False)),
                ('name_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict_telegram_bot.studysubject', verbose_name='Предмет')),
                ('stud_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='predict_telegram_bot.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
        migrations.CreateModel(
            name='PointsPerSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_score', models.FloatField(default=0, verbose_name='Балл за предмет')),
                ('attending_classes', models.FloatField(default=0, verbose_name='Посещение')),
                ('name_subject', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='predict_telegram_bot.studysubject', verbose_name='Предмет')),
                ('stud_id', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='predict_telegram_bot.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Баллы в семестре',
                'verbose_name_plural': 'Баллы в семестре',
            },
        ),
        migrations.CreateModel(
            name='SchoolExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=15, verbose_name='Название экзамена')),
                ('exam_score', models.FloatField(default=0, verbose_name='Балл')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SchoolExam', to='predict_telegram_bot.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Школьный экзамен',
                'verbose_name_plural': 'Школьные экзамены',
                'unique_together': {('exam_name', 'stud_id')},
            },
        ),
    ]
